### ISSUE TITLE
Plan a route open existing one Suite a No 2 Issue 2

### ISSUE THREAD

**Issue by fixifoxy** [OsmAnd-Rendering/Motorcycle#12]
je prends souvent les tracks publies par les syndicats  d initiative, office de tourisme.
et il m arrive que je me trouve dans des conditions de terrain non desire. 
Voir  le gpx-file Buschenschank entre les 2 waymarks. Affreux terrain Mountain Bike. 
Il est donc mon intention d examiner un track publie
avec la function
"plan a route"
"open existing track"
utilisant les profils de  Christoph
ou gros_trail 
ou petit trail.
C est j ai fait.
les resultats compiled in the attached zip-File.
Qu est-ce que t en pense christoph
 
 
[PlanaRoutewithexisting.zip](https://github.com/OsmAnd-Rendering/Motorcycle/files/12110237/PlanaRoutewithexisting.zip)

**Comment by cricri-du-lauragais** [comment]
I'm not sure I understand, but the calculation and accuracy of the various routings is based on whether or not the paths in OpenStreetMap are accurate.
if the single track is incorrectly defined as a double track, the "gros trail" routing can take it.
if the path is noted in OpenStreetMap as "mtb:scale=0" (a very easy and clean path), the "small trail" routing may pass over it.
when the path has no particular attribute in openstreetmap, "gros trail" routing without "si chemin sec" will not take it,
if the "si chemin sec" option is active, routing can take it over a short distance.

**Comment by fixifoxy** [comment]
please delete
