### ISSUE TITLE
Impossible d'ouvrir le fichier OSF

### ISSUE THREAD

**Issue by tomd1309** [OsmAnd-Rendering/Motorcycle#16]
Bonjour, je viens de changer de téléphone lorsque j'ai voulu importer le profil il ne passe rien dans l'application (rien à importer). J'ai essayé avec d'autre fichier OSF et ça fonctionne. Pareil si j'exporte un profil et que je le réimporte après ca fonctionne. Mais le fichier Installation.osf ne s'ouvre pas.

**Comment by cricri-du-lauragais** [comment]
effectivement j'ai le même soucis sur mon téléphone android 14
par contre pas de problème avec la même version (la dernière) sous windows 11

**Comment by cricri-du-lauragais** [comment]
j'ai corrigé le fichier osf, je pense que ça fonctionne maintenant ;)

**Comment by tomd1309** [comment]
Effectivement tout fonctionne, merci beaucoup
