### ISSUE TITLE
Width of Border Lines

### ISSUE THREAD

**Issue by FriedelXT** [OsmAnd-Rendering/Motorcycle#2]
hi!

I am very happy with your style and routing. Congratulation for your work!

Can you please do the width of country border thicker? By zoom in, cant see so good the borders. Specially while driving.
I did it in hiking style already for myself. But I am very bad in style coding, so it is quick and dirty and I dont know excatly what i do.
Something like this, I mean:

![IMG_5130](https://user-images.githubusercontent.com/75690375/180883410-30191c0e-bea5-4249-b7ae-710cd14c130a.jpg)

.

**Comment by cricri-du-lauragais** [comment]
hello, boundaries are defined at line 4484 into file enduro.render.xml
lines 4486/87/88 are states

line 4500 define admin level 4 (french "région" like "occitanie")
city are admin level 8 and are not represented in the style (see osm wiki https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#admin_level=*_Country_specific_values)

you can copy chapter <apply></apply> from line 4489 to 4497 to the chapter <apply></apply> 4503 to 4507 it is the same by default style ;)

**Comment by FriedelXT** [comment]
i found a possibility. Thanks

<case maxzoom="6" strokeWidth="3:3" strokeWidth_0="1.3:1"/>
				<case maxzoom="8" strokeWidth="4:4" strokeWidth_0="1.5:1"/>
				<case minzoom="9" strokeWidth="6:6" strokeWidth_0="1.9:1"/>

**Comment by cricri-du-lauragais** [comment]
done
