### ISSUE TITLE
Crash avec OpenGL

### ISSUE THREAD

**Issue by arncor** [OsmAnd-Rendering/Motorcycle#8]
Salut cri-cri,

Merci pour ton super boulot sur les rendering et le reste.
Je viens de passer de Osmand+ Fdroid à la version Playstore pour profiter du rendu plus rapide grâce à l'openGL, mais hélas, pas moyen de faire fonctionner avec ton fichier render, ça crash au lancement de l'app, ou, si je démarre avec le render Osmand puis que je sélectionne ton rendu.

Avec le render offroad, j'ai seulement un crash au lancement de l'app, mais apparemment c'est dû à un bug d'init des rendering vs les dépendances des rendering. Ce sera résolu dans Osmand 4.3

En attendant, je ne comprends pas pourquoi ça se comporte différemment de ton fichier rendering.

J'ai un Ulefone Armor6E sous Android9.

@+

**Comment by cricri-du-lauragais** [comment]
Salut, difficile à dire
chez moi l' OpenGL ne s'est mis à fonctionner que depuis la version 4.2.7
l'openGL fonctionne aussi depuis peu sous ChromeOS (dernière version de chrome)
ça reste en beta sous Android, difficile de tester quoique ce soit :(
en tout cas le rendu fonctionne en openGL sur le pixel 4a de ma femme (Android 13)
mon Samsung A33 Android 12
Chrome OS > Android 9
uniquement la version du playstore.

Désolé de ne pas pouvoir t'en dire plus.

**Comment by cricri-du-lauragais** [comment]
en lisant les commentaires de l'issue, je vois que j'ai parfois le message d'incompatibilité lors des maj live de la carte sans qu' OsmAnd ne soit lancé.
sur mes configurations j'ai un de mes profils en profil par défaut auquel est attribué mon rendu, ça évite peut-être les soucis d'ordre d'initialisation ?

**Comment by arncor** [comment]
Avec la version Playstore, je n'ai plus (comme avec Fdroid) les _live map updates_ car je n'ai pas Osmand Pro.

J'ai aussi un profil avec ton rendu par defaut, mais ce profil n'est pas celui par défaut au lancement de l'app.
Quand j'ouvre osmand, pas de souci jusqu'à ce que je choisisse ce profil et là l'app crash.
Alors qu'avec le mode offroad, tant qu'il n'est pas affiché dès le lancement de l'app, je peux switcher dessus et ça ne _crash_ pas

**Comment by arncor** [comment]
Update : ça marche à nouveau !
Je viens de tester avec OsmAnd+ 4.3.6 et en ayant réinstallé le fichier de rendering via le fichier installation.osf
