### ISSUE TITLE
Profil gros_trail with Osmand Plan route and Snap  to the road

### ISSUE THREAD

**Issue by fixifoxy** [OsmAnd-Rendering/Motorcycle#9]
Je suppose que Christoph et cricri sont synonym?

Ici c est Horst d Autriche .

Je viens de discuter l usage du profil gros_trail  in  
OSMAND avec 
"Plan a route" 
using an existing route
 and snapping the result to my profile selectionne  et c est ton profile gros_trail.
Mais cela ne finissait pas. Tu trouveras ma discussion sous Github Osmand # 17045.
Merci
Horst

**Comment by cricri-du-lauragais** [comment]
depuis la version 4.4 les options ont changées de place,
maintenant c'est pour Android

- ouverture du gpx dans osmand
- clic sur la trace affichée sur la carte
- clic sur l'icone du crayon (modifier la trace)
- options
- déplacer sur les routes
choisir parmi les routages proposés
